NextTask/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings  # Para acceder a las configuraciones de MEDIA_URL y MEDIA_ROOT
from django.conf.urls.static import static  # Para servir archivos estáticos y multimedia
from . import views
from django.conf.urls.i18n import i18n_patterns

# Rutas que no deben tener prefijo de idioma (como las APIs)
urlpatterns = [path('messaging/', include('Messaging.urls')),]  # Incluye las rutas de la app Messaging sin i18n]

# Rutas con soporte de internacionalización
urlpatterns += i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path('admin/', admin.site.urls),
    path('users/', include('Users.urls')),  # Incluye las urls de la app Users
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),  # Ruta para cerrar sesión
    path('auth/', include('social_django.urls', namespace='social')),  # Ruta para autenticación social (Google, etc.)
    path('', views.home, name='home'),  # Ruta para la página principal
    path('projects/', include('Projects.urls')),  # Incluye las rutas de la app Projects
    path('notifications/', include('Notifications.urls')),  # Incluye las rutas de la app Notifications sin i18n
    path('reports/', include('Reports.urls')),    # Rutas del módulo Reports
    path('payments/', include('Payments.urls')),
)

# Configuración para servir archivos multimedia durante el desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Projects/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    
    # Function to create a new project
    path('createProject/', views.create_project, name='createProject'),  
    
    # Function to view the client's home page
    path("home-Client/", views.home_client, name="home_client"),  
    
    # Function to view project details
    path('project/<int:project_id>/', views.project_detail, name='project_detail'),  
    
    # Function to edit an existing project
    path('project/edit/<int:project_id>/', views.edit_project, name='edit_project'),  
    
    # Function to delete a project
    path('delete_project/<int:project_id>/', views.delete_project, name='delete_project'),  

    # Milestones
    # Function to add a milestone to a project
    path('projects/<int:project_id>/add_milestone/', views.create_milestone, name='add_milestone'),  
    
    # Function to edit a milestone
    path('milestones/<int:milestone_id>/edit/', views.edit_milestone, name='edit_milestone'),  
    
    # Function to view milestone details
    path('milestone/<int:pk>/', views.milestone_detail_view, name='milestone_detail'),  
    
    # Function to delete a milestone
    path('delete_milestone/<int:milestone_id>/', views.delete_milestone, name='delete_milestone'),  

    # Tasks
    # Function to create a task for a milestone
    path('milestone/<int:milestone_id>/add_task/', views.create_task, name='create_task'),  
    
    # Function to edit an existing task
    path('task/<int:task_id>/edit/', views.edit_task, name='edit_task'),  
    
    # Function to delete a task
    path('task/<int:task_id>/delete/', views.delete_task, name='delete_task'),  
    
    # Function to view task details
    path('task/<int:task_id>/', views.task_detail, name='task_detail'),  
    
    # Freelancer search and profiles
    # Function to search for freelancers in a project
    path('projects/<int:project_id>/search_freelancer/', views.search_freelancer, name='search_freelancer'),  
    
    # Function to view freelancer's profile
    path('contract/<int:project_id>/<int:freelancer_id>/', views.freelancer_profile, name='freelancer_profile'),  

    # Function to create a project-freelancer association
    path('project/<int:project_id>/freelancer/<int:freelancer_id>/contract/', views.create_project_freelancer_association, name='create_project_freelancer_association'),  
    
    # Function to manage freelancer applications for a project
    path('projects/<int:project_id>/applications/', views.manage_applications, name='manage_applications'),  

    # Function to manage freelancer's profile view
    path('view_freelancer_profile/<int:project_id>/<int:freelancer_id>/', views.freelancer_profile_manage, name='view_freelancer_profile_manage'),  

    # Search and Apply to Projects
    # Function for searching projects
    path('search_projects/', views.search_projects, name='search_projects'),  
    
    # Function to view a public project
    path('project/view/<int:project_id>/', views.view_project_search, name='view_project_search'),  
    
    # Function to apply to a project
    path('project/apply/<int:project_id>/', views.apply_to_project, name='apply_to_project'),  
    
    # Function for application confirmation
    path('application-confirmation/', views.application_confirmation, name='application_confirmation'),  
    
    # Freelancer-specific project views
    # Function to view a project from the freelancer's perspective
    path('freelancer/project/<int:project_id>/', views.project_detail_freelancer, name='project_detail_freelancer'),  
    
    # Function to view milestone details for freelancers
    path('milestone/<int:pk>/details/', views.milestone_detail_view_freelancer, name='milestone_detail_freelancer'),  
    
    # Function to edit a task for freelancers
    path('tasks/<int:task_id>/edit/', views.edit_task_freelancer, name='edit_task_freelancer'),  
    
    # Function to view task details for freelancers
    path('freelancer/task/<int:task_id>/', views.task_detail_view_freelancer, name='task_detail_freelancer'),  
    
    # Function to manage freelancer applications
    path('projects/freelancer/manage_applications/', views.manage_applications_freelancer, name='manage_applications_freelancer'),  
    
    # Function to view freelancers associated with a specific project
    path('projects/<int:project_id>/freelancers/', views.freelancers_in_project, name='freelancers_in_project'), 
    
    path('projects/deleted/', views.deleted_projects, name='deleted_projects'),
    path('projects/<int:project_id>/restore/', views.restore_project, name='restore_project'),
    path('projects/<int:project_id>/permanent_delete/', views.permanently_delete_project, name='permanent_delete_project'),
    
    path('milestones/<int:project_id>/deleted/', views.deleted_milestones, name='deleted_milestones'),
    path('milestones/<int:milestone_id>/restore/', views.restore_milestone, name='restore_milestone'),
    path('milestones/<int:milestone_id>/permanent_delete/', views.permanently_delete_milestone, name='permanent_delete_milestone'),
    
    path('tasks/<int:milestone_id>/deleted/', views.deleted_tasks, name='deleted_tasks'),
    path('tasks/<int:task_id>/restore/', views.restore_task, name='restore_task'),
    path('tasks/<int:task_id>/permanent_delete/', views.permanently_delete_task, name='permanent_delete_task'),

    path('redirect-to-payments/', views.redirect_to_client_payment_history, name='redirect_to_client_payments'),
    path('redirect-to-payments/', views.redirect_to_freelancer_payment_history, name='redirect_to_freelancer_payments'),

]

Users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    # URL for freelancer signup
    path('signup/freelancer/', views.freelancer_signup, name='register_freelancer'),

    # URL for client signup
    path('signup/client/', views.client_signup, name='client_signup'),

    # URL for registering education information
    path('education/register/', views.education_register_view, name='education_register'),

    # URL for registering work experience
    path('work-experience/register/', views.work_experience_register_view, name='work_experience_register'),

    # URL for registering certifications
    path('certification/register/', views.certification_register_view, name='certification_register'),

    # URL for registering portfolio links
    path('portfolio/register/', views.portfolio_register_view, name='portfolio_register'),

    # URL for registering languages
    path('languages/register/', views.register_languages_view, name='register_languages'),

    # URL for registering skills
    path('skills/register/', views.register_skills_view, name='register_skills'),

    # URL for user login
    path('login/', views.user_login, name='login'),

    # URL for welcome page
    path('welcome/', views.welcome, name='welcome'),

    # Home page for freelancers (dashboard)
    path("Home-Freelancer/", views.home_freelancer, name="home_freelancer"),

    # URL for changing password client
    path("changePasswordClient/", views.change_password_client, name="change_password_client"),

    # URL for changing password freelancer
    path("changePasswordFreelancer/", views.change_password_freelancer, name="change_password_freelancer"),

    # URL for password recovery
    path("passwordRecovery/", views.password_recovery, name="password_recovery"),

    # URL for verfy code validation email
    path('verify_code/<int:user_id>/', views.verify_code, name='verify_code'),

    # URL for password reset
    path('reset_password/<int:user_id>/', views.reset_password, name='reset_password'),

    # URL for profile settings freelancer
    path("profileSettingsFreelancer/", views.profile_settings_freelancer, name="profile_settings_freelancer"),

    # URL for profile settings client
    path("profileSettingsClient/", views.profile_settings_client, name="profile_settings_client"),

    # URL for searching freelancers
    path('search/', views.search_freelancers, name='search_freelancers'),

    # URL for viewing a freelancer's profile
    path('freelancer/<int:id>/', views.freelancer_profile, name='freelancer_profile'),

    # URL for searching clients
    path('search_clients/', views.search_clients, name='search_clients'),

    # URL for viewing a client's profile
    path('client/<int:id>/', views.client_profile, name='client_profile'),

]

Payments/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from Users.models import FreelancerProfile, ClientProfile
from Projects.models import Project
from datetime import timedelta
from django.utils import timezone
from django.core.exceptions import ValidationError

class Payment(models.Model):
    """
    Represents a one-time payment associated with a project and a freelancer.
    
    Attributes:
        freelancer (FreelancerProfile): ForeignKey to the FreelancerProfile model.
        project (Project): ForeignKey to the Project model.
        amount (Decimal): The amount to be paid.
        status (str): The status of the payment (pending or paid).
    """
    
    class PaymentStatus(models.TextChoices):
        PENDING = 'pending', _('Pending')
        PAID = 'paid', _('Paid')

    freelancer = models.ForeignKey(FreelancerProfile, on_delete=models.CASCADE, related_name='payments')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='payments')
    amount = models.DecimalField(max_digits=10, decimal_places=2)  # Define el monto del pago
    status = models.CharField(
        max_length=10,
        choices=PaymentStatus.choices,
        default=PaymentStatus.PENDING
    )
    client = models.ForeignKey('Users.ClientProfile', on_delete=models.CASCADE, related_name='payments')
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Payment of {self.amount} for {self.freelancer.user.username} - Status: {self.status}"
    
class PeriodicPayment(models.Model):
    """
    Configuración para pagos periódicos entre un cliente y un freelancer en un proyecto.
    """
    class Frequency(models.TextChoices):
        DAILY = 'daily', _('Daily')
        WEEKLY = 'weekly', _('Weekly')
        MONTHLY = 'monthly', _('Monthly')

    freelancer = models.ForeignKey(FreelancerProfile, on_delete=models.CASCADE, related_name='periodic_payments')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='periodic_payments')
    client = models.ForeignKey(ClientProfile, on_delete=models.CASCADE, related_name='periodic_payments')
    amount = models.DecimalField(max_digits=10, decimal_places=2)  # Monto por cada periodo
    frequency = models.CharField(max_length=10, choices=Frequency.choices, default=Frequency.WEEKLY)
    start_date = models.DateField()  # Fecha de inicio del pago periódico
    end_date = models.DateField(null=True, blank=True)  # Fecha opcional de fin del pago periódico
    next_payment_date = models.DateField()  # Fecha del próximo pago programado

    def __str__(self):
        return f"{self.freelancer.user.username} - {self.project.title} ({self.frequency})"
    
    def generate_next_payment_date(self):
        """
        Genera la próxima fecha de pago de acuerdo con la frecuencia establecida.
        """
        if self.frequency == self.Frequency.DAILY:
            return self.next_payment_date + timedelta(days=1)
        elif self.frequency == self.Frequency.WEEKLY:
            return self.next_payment_date + timedelta(weeks=1)
        elif self.frequency == self.Frequency.MONTHLY:
            return self.next_payment_date + timedelta(days=30)  # Aproximado para meses

    def create_pending_payment(self):
        """
        Crea un registro de pago puntual pendiente cuando llega la fecha de pago.
        """
        from Payments.models import Payment  # Importar modelo de Payment para evitar importaciones circulares
        
        if self.next_payment_date <= timezone.now().date():
            Payment.objects.create(
                freelancer=self.freelancer,
                project=self.project,
                amount=self.amount,
                status=Payment.PaymentStatus.PENDING,
                client=self.client
            )
            self.next_payment_date = self.generate_next_payment_date()  # Actualiza la próxima fecha de pago
            self.save()

    def clean(self):
        """
        Valida que solo exista un pago periódico para cada freelancer y proyecto.
        """
        if PeriodicPayment.objects.filter(freelancer=self.freelancer, project=self.project).exists():
            raise ValidationError(_('There is already a periodic payment for this freelancer on this project.'))

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['freelancer', 'project'], name='unique_periodic_payment_per_project')
        ]

Reports/forms.py
from django import forms
from Projects.models import Project
from django.core.exceptions import ValidationError


class ReportFilterForm(forms.Form):
    start_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'})
    )
    end_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'})
    )
    metrics = forms.MultipleChoiceField(
        choices=[
            ('progress', 'Progress of the Projects'),
            ('budget', 'Budget used'),
            ('milestones', 'Milestones status'), 
            ('tasks', 'Tasks status')
        ],
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-check-input'})
    )
    project = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Extrae el usuario de los argumentos
        super().__init__(*args, **kwargs)

        # Verifica si hay un usuario y carga los proyectos correspondientes
        if user:
            projects = Project.objects.filter(client=user.clientprofile)
            self.fields['project'].choices = [(project.id, project.title) for project in projects]
        else:
            self.fields['project'].choices = []  # Si no hay usuario, no muestra proyectos

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")
        project_id = cleaned_data.get("project")
        
        if start_date and end_date and start_date > end_date:
            self.add_error("start_date", "The start date cannot be after the end date.")
            self.add_error("end_date", "The end date cannot be before the start date.")
            
        if project_id:
            project = Project.objects.get(id=project_id)
            project_start_date = project.start_date  # Ajusta al nombre correcto del campo en el modelo
            project_end_date = project.actual_end_date  # Ajusta al nombre correcto del campo en el modelo
            
            if start_date and start_date < project_start_date:
                self.add_error("start_date", "The start date is before the project start date.")
                
            if end_date and project_end_date and end_date > project_end_date:
                self.add_error("end_date", "The end date is after the project end date.")

        return cleaned_data

Projects/templates/Projects/freelancer_profile_manage.html
{% extends 'Users/baseClient.html' %}
{% load static %}

<!-- This is to view the profile in freelancer in manage-->
{% block content %}



<div class="container">
    
    <!-- Encabezado del perfil -->
    {% include 'Users/profile_header.html' %}

    <!-- Detalles del perfil -->
    {% include 'Users/freelancer_details.html' %}

</div>





{% endblock %}

Projects/templates/Projects/milestone_detail_freelancer.html
{% extends 'Users/baseFreelancer.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<head>
    <!-- django-quill-editor Media -->
    {% include 'django_quill/media.html' %}

    <style>
        .quill-content {
            overflow-wrap: break-word;
            word-wrap: break-word;
            word-break: break-word;
            overflow: hidden;
            max-width: 100%;
        }

        .quill-content img {
            max-width: 100%;
            height: auto;
            display: block;
        }
    </style>
</head>

<!-- Page Header -->
<div>
    <h3 class="text-24 fw-bold text-dark-300 mb-2">{% trans "Milestone Details:" %} {{ milestone.title }}</h3>
    <ul class="d-flex align-items-center gap-2">
        <li class="text-dark-200 fs-6">{% trans "Dashboard" %}</li>
        <li>
            <svg xmlns="http://www.w3.org/2000/svg" width="5" height="11" viewBox="0 0 5 11" fill="none">
                <path d="M1 10L4 5.5L1 1" stroke="#5B5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
        </li>
        <li class="text-lime-300 fs-6">{% trans "Milestone Details" %}</li>
    </ul>
</div>

<!-- Milestone Info -->
<div class="row justify-content-center">
    <div class="col-xl-8">
        <div class="d-flex flex-column gap-4">
            <!-- Milestone Info Card -->
            <div class="gig-info-card">
                <div class="gig-info-header">
                    <h4 class="text-18 fw-semibold text-dark-300">{% trans "Milestone Info" %}</h4>
                </div>
                <div class="gig-info-body bg-white">
                    <div class="row g-4">
                        <!-- Título del hito -->
                        <div class="col-12">
                            <div class="form-container">
                                <label class="form-label">{% trans "Milestone Title" %}</label>
                                <div class="form-control shadow-none readonly-field">{{ milestone.title }}</div>
                            </div>
                        </div>
                        <!-- Fecha de vencimiento -->
                        <div class="col-md-6">
                            <div class="form-container">
                                <label class="form-label">{% trans "Due Date" %}</label>
                                <div class="form-control shadow-none readonly-field">{{ milestone.due_date }}</div>
                            </div>
                        </div>
                        <!-- Categoría -->
                        <div class="col-md-6">
                            <div class="form-container">
                                <label class="form-label">{% trans "Category" %}</label>
                                <div class="form-control shadow-none readonly-field">{{ milestone.get_category_display }}</div>
                            </div>
                        </div>
                        <!-- Descripción -->
                        <div class="col-12">
                            <div class="form-container">
                                <label class="form-label">{% trans "Description" %}</label>
                                <div class="quill-content">{{ milestone.description.html|safe }}</div>
                            </div>
                        </div>
                        <!-- Archivo -->
                        <div class="col-6">
                            <div class="form-container">
                                <label class="form-label">{% trans "File" %}</label>
                                {% if milestone.file %}
                                    <a href="{{ milestone.file.url }}" class="w-btn-secondary-lg">{% trans "Download File" %}</a>
                                {% else %}
                                    <p>{% trans "No file uploaded" %}</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="text mt-4">
                <div class="button-group">
                    <a href="{% url 'project_detail_freelancer' milestone.project.id %}" class="w-btn-danger-lg">{% trans "Back" %}</a>
                </div>
                <p>.</p>
                <p></p>
            </div>
        </div>
    </div>
</div>

<!-- Lista de Tareas -->
<div>
    <h3 class="text-20 fw-semibold text-dark-300 mb-3">{% trans "Tasks" %}</h3>

    <!-- Verifica si hay tareas -->
    {% if tasks.all %}
        <table class="w-100 dashboard-table">
            <thead class="pb-3">
                <tr>
                    <th scope="col" class="ps-4">{% trans "Task Title" %}</th>
                    <th scope="col">{% trans "Due Date" %}</th>
                    <th scope="col">{% trans "Status" %}</th>
                    <th scope="col">{% trans "Priority" %}</th>
                    <th scope="col" class="text-end pe-5">{% trans "Actions" %}</th>
                </tr>
            </thead>
            <tbody>
                <!-- Itera sobre cada tarea asociada al hito y filtrada por freelancer -->
                {% for task in tasks %}
                <tr>
                    <!-- Título de la tarea -->
                    <td onclick="window.location.href='{% url 'task_detail_freelancer' task.id %}'" style="cursor: pointer;" id="task_detail_on_click">
                        <div class="d-flex gap-3 align-items-center project-name">
                            <div>
                                <p class="text-dark-200">{{ task.title }}</p>
                            </div>
                        </div>
                    </td>
                    
                    <!-- Fecha de vencimiento -->
                    <td onclick="window.location.href='{% url 'task_detail_freelancer' task.id %}'" style="cursor: pointer;" class="text-dark-200">
                        {{ task.due_date }}
                    </td>
                    
                    <!-- Estado de la tarea -->
                    <td onclick="window.location.href='{% url 'task_detail_freelancer' task.id %}'" style="cursor: pointer;" class="text-dark-200">
                        {{ task.get_status_display }}
                    </td>
                    
                    <!-- Prioridad de la tarea -->
                    <td onclick="window.location.href='{% url 'task_detail_freelancer' task.id %}'" style="cursor: pointer;" class="text-dark-200">
                        {{ task.get_priority_display }}
                    </td>
                    
                    <!-- Acciones (Solo Editar) -->
                    <td>
                        <div class="d-flex justify-content-end gap-2">
                            <a href="{% url 'edit_task_freelancer' task.id %}" class="btn btn-primary btn-sm">{% trans "Edit" %}</a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <!-- Mensaje si no hay tareas -->
        <p>{% trans "No tasks available for this milestone." %}</p>
    {% endif %}
</div>


{% endblock %}

Projects/templates/Projects/task_info_edit.html
{% load static %}
{% load i18n %}


<div class="gig-info-card">
    <div class="gig-info-header">
        <h4 class="text-18 fw-semibold text-dark-300">{% trans "Task Info" %}</h4>
        </div>
        <div class="gig-info-body bg-white">
        <div class="row g-4">
            <!-- Title -->
            <div class="col-12">
            <div class="form-container">
                <label for="id_title" class="form-label">{% trans "Task Title" %} <span class="text-lime-300">*</span></label>
                {{ form.title }} <!-- Campo del título -->
                {% if form.title.errors %}
                <div class="error text-danger">{{ form.title.errors }}</div>
                {% endif %}
            </div>
            </div>
            <!-- Start Date -->
            <div class="col-md-6">
                <div class="form-container">
                    <label for="id_start_date" class="form-label">{% trans "Start Date" %} <span class="text-lime-300">*</span></label>
                    {{ form.start_date }} <!-- Campo de la fecha de inicio -->
                    {% if form.start_date.errors %}
                    <div class="error text-danger">{{ form.start_date.errors }}</div>
                    {% endif %}
                </div>
            </div>
            <!-- Due Date -->
            <div class="col-md-6">
            <div class="form-container">
                <label for="id_due_date" class="form-label">{% trans "Due Date" %} <span class="text-lime-300">*</span></label>
                {{ form.due_date }} <!-- Campo de la fecha de vencimiento -->
                {% if form.due_date.errors %}
                <div class="error text-danger">{{ form.due_date.errors }}</div>
                {% endif %}
            </div>
            </div>
            <!-- Priority -->
            <div class="col-md-6">
            <div class="form-container">
                <label for="id_priority" class="form-label">{% trans "Priority" %}<span class="text-lime-300">*</span></label>
                {{ form.priority }} <!-- Selector de prioridad -->
            </div>
            </div>
            <!-- Status -->
            <div class="col-md-6">
            <div class="form-container">
                <label for="id_status" class="form-label">{% trans "Status" %}<span class="text-lime-300">*</span></label>
                {{ form.status }} <!-- Selector de estado -->
            </div>
            </div>
            <!-- Assigned to -->
            <div class="col-md-6">
            <div class="form-container">
                <label for="id_assigned_to" class="form-label">{% trans "Assigned To" %}<span class="text-lime-300">*</span></label>
                {{ form.assigned_to }} <!-- Selector de asignado -->
            </div>
            </div>
            <!-- Attachments -->
            <div class="col-12">
            <label for="id_attachments" class="form-label">{% trans "Attachments (optional)" %}</label>
            {{ form.attachments }} <!-- Campo de archivo -->
            {% if task.attachments %}
                <p>{% trans "Current file" %}: <a href="{{ task.attachments.url }}">{% trans "Download current file" %}</a></p>
            {% endif %}
            {% if form.attachments.errors %}
                <div class="error text-danger">{{ form.attachments.errors }}</div>
            {% endif %}
            </div>
            
            <!-- Description -->
            <div class="col-12">
            <label for="id_description" class="form-label">{% trans "Description" %}</label>
            {{ form.description }} <!-- Editor Quill -->
            {% if form.description.errors %}
                <div class="error text-danger">{{ form.description.errors }}</div>
            {% endif %}
            </div>
        </div>
    </div>
</div>

Projects/templates/Projects/task_info_view.html
{% load static i18n %}

<div class="gig-info-card">
    <div class="gig-info-header">
        <h4 class="text-18 fw-semibold text-dark-300">{% trans "Task Info" %}</h4>
    </div>
    <div class="gig-info-body bg-white">
        <div class="row g-4">
            <!-- Título de la tarea -->
            <div class="col-12">
                <div class="form-container">
                    <label class="form-label">{% trans "Task Title" %}</label>
                    <div class="form-control shadow-none readonly-field">{{ task.title }}</div>
                </div>
            </div>
            
            <!-- Fecha de vencimiento -->
            <div class="col-md-6">
                <div class="form-container">
                    <label class="form-label">{% trans "Due Date" %}</label>
                    <div class="form-control shadow-none readonly-field">{{ task.due_date }}</div>
                </div>
            </div>
            <!-- Prioridad -->
            <div class="col-md-6">
                <div class="form-container">
                    <label class="form-label">{% trans "Priority" %}</label>
                    <div class="form-control shadow-none readonly-field">{{ task.get_priority_display }}</div>
                </div>
            </div>
            <!-- Estado -->
            <div class="col-md-6">
                <div class="form-container">
                    <label class="form-label">{% trans "Status" %}</label>
                    <div class="form-control shadow-none readonly-field">{{ task.get_status_display }}</div>
                </div>
            </div>
            <!-- Asignación -->
            <div class="col-md-6">
                <div class="form-container">
                    <label class="form-label">{% trans "Assigned to" %}</label>
                    <div class="form-control shadow-none readonly-field">
                        {% if task.assigned_to %}
                            {{ task.assigned_to.user.username }}
                        {% else %}
                            {% trans "Not assigned" %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <!-- Archivo -->
            <div class="col-6">
                <div class="form-container">
                    <label class="form-label">{% trans "File" %}</label>
                    {% if task.attachments %}
                        <a href="{{ task.attachments.url }}" class="w-btn-secondary-lg">{% trans "Download File" %}</a>
                    {% else %}
                        <p>{% trans "No file uploaded" %}</p>
                    {% endif %}
                </div>
            </div>

            <!-- Descripción -->
            <div class="col-12">
                <div class="form-container">
                    <label class="form-label">{% trans "Description" %}</label>
                    <div class="quill-content">
                        {{ task.description.html|safe }}
                    </div>
                </div>
            </div>
                               
        </div>
    </div>
</div>